export const FETCH_DETAIL_PAGE_REQUEST = 'FETCH_DETAIL_PAGE_REQUEST';
export const FETCH_DETAIL_PAGE_SUCCESS = 'FETCH_DETAIL_PAGE_SUCCESS';
export const FETCH_DETAIL_PAGE_FAIL = 'FETCH_DETAIL_PAGE_FAIL';