export const FETCH_PLACE_REQUEST = 'FETCH_PLACE_REQUEST';
export const FETCH_PLACE_SUCCESS = 'FETCH_PLACE_SUCCESS';
export const FETCH_PLACE_FAIL = 'FETCH_PLACE_FAIL';
export const SELECT_FILM = 'SELECT_FILM';
export const SELECT_VIEWINGTIMES = 'SELECT_VIEWINGTIMES';
