export const FETCH_INFORMATION_REQUEST = 'FETCH_INFORMATION_REQUEST';
export const FETCH_INFORMATION_SUCCESS = 'FETCH_INFORMATION_SUCCESS';
export const FETCH_INFORMATION_FAIL = 'FETCH_INFORMATION_FAIL';