export const FETCH_DETAIL_MOVIE_REQUEST = 'FETCH_DETAIL_MOVIE_REQUEST';
export const FETCH_DETAIL_MOVIE_SUCCESS = 'FETCH_DETAIL_MOVIE_SUCCESS';
export const FETCH_DETAIL_MOVIE_FAIL = 'FETCH_DETAIL_MOVIE_FAIL';
export const SELECT_ACTION = 'SELECT_ACTION'
export const TRANSFER_PAGE = 'TRANSFER_PAGE'
export const GET_COMMENT = 'GET_COMMENT'