export const FETCH_ALL_MOVIE_REQUEST = 'FETCH_ALL_MOVIE_REQUEST';
export const FETCH_ALL_MOVIE_SUCCESS = 'FETCH_ALL_MOVIE_SUCCESS';
export const FETCH_ALL_MOVIE_FAIL = 'FETCH_ALL_MOVIE_FAIL';
export const SELECT_ACTION = 'SELECT_ACTION'