export const FETCH_ALL_MOVIE_ADMIN_REQUEST = 'FETCH_ALL_MOVIE_ADMIN_REQUEST';
export const FETCH_ALL_MOVIE_ADMIN_SUCCESS = 'FETCH_ALL_MOVIE_ADMIN_SUCCESS';
export const FETCH_ALL_MOVIE_ADMIN_FAIL = 'FETCH_ALL_MOVIE_ADMIN_FAIL';
export const SELECT_ACTION = 'SELECT_ACTION'